fos_user:
    db_driver: orm
    user_class: 'App\Entity\User'
    firewall_name: main
    from_email:
        address: 'infoasl@uco.es'
        sender_name: 'Aula de Software Libre'
    group:
        group_class: 'App\Entity\Group'
