knp_menu:
    twig:
        template: '@HarmonyUi/menu/semantic_2_menu.html.twig'

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    # KnpMenuBundle
    App\Menu\Builder:
        arguments: ['@knp_menu.factory']
        public: true
        tags:
        - { name: 'knp_menu.menu_builder', method: 'sidebarMenu', alias: 'sidebarMenu'}
        - { name: 'knp_menu.menu_builder', method: 'mainMenu', alias: 'mainMenu'}

#    App\Menu\SemanticMenuRenderer:
#        arguments:
#        - '@knp_menu.matcher'
#        - '%knp_menu.renderer.list.options%'
#        - '%kernel.charset%'
#        public: true
#        tags:
#        - { name: 'knp_menu.renderer', alias: 'semantic'}
#
