services:
    _defaults:
        autowire: true
        public: false
    pagerfanta.view.idea.main:
        class: Pagerfanta\View\OptionableView
        arguments:
        - '@pagerfanta.view.semantic_ui_translated'
        - { proximity: 1, prev_message: '<i class="angle double left icon"></i>', next_message: '<i class="angle double right icon"></i>', css_container_class: 'ui pagination menu' }
        tags: [{ name: pagerfanta.view, alias: idea_main }]
