#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

help:
    path: /help
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template:  'frontend/static/help.html.twig'
        maxAge:    86400
        sharedAge: 86400
