name: CI/CD

on:
    push:
    pull_request:

jobs:
    images:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.repository == 'aulasoftwarelibre/idea' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/releases/') || startsWith(github.ref, 'refs/tags/v') )
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-
            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ secrets.CR_USER }}
                    password: ${{ secrets.CR_PAT }}

            -
                name: Extract tag name
                id: extract_tag
                run: echo "::set-output name=tag::$(echo ${GITHUB_REF##*/})"

            -
                name: Build and push php
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    target: idea_php
                    tags: |
                        ghcr.io/aulasoftwarelibre/idea-php:latest
                        ghcr.io/aulasoftwarelibre/idea-php:${{ steps.extract_tag.outputs.tag }}
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
            -
                name: Build and push httpd
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    target: idea_httpd
                    tags: |
                        ghcr.io/aulasoftwarelibre/idea-httpd:latest
                        ghcr.io/aulasoftwarelibre/idea-httpd:${{ steps.extract_tag.outputs.tag }}
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
